# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 22:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('followees', models.ManyToManyField(blank=True, related_name='_photographer_followees_+', to='photographers.Photographer')),
                ('followers', models.ManyToManyField(blank=True, related_name='_photographer_followers_+', to='photographers.Photographer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
