# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20180829_2341'),
        ('photographers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='feed',
            field=models.ManyToManyField(blank=True, null=True, to='photos.Photo'),
        ),
    ]
