# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0002_photographer_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='feed',
            field=models.ManyToManyField(blank=True, to='photos.Photo'),
        ),
    ]
