# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20180829_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='file',
            new_name='image',
        ),
    ]
